### ISSUE TITLE
Ajouter un libellé pour l'affichage sur les critères

### ISSUE THREAD

**Issue by arnaudlevy** [Dannebicque/redigeTonBut#5]
[1. Mettre en oeuvre sa/ses compétences](https://orebut.iut.fr/labset/criteres/evaluation/1)

s'affiche dans le show de la SAE en "Vise la compétence..."

Par ailleurs l'url crash

**Comment by arnaudlevy** [comment]
<img width="1710" alt="image" src="https://user-images.githubusercontent.com/2088968/216570322-cb90b51b-7e93-4f99-866f-d58426e1e2ce.png">

Ajouter aussi un champ de description du critère, que l'on ajouterait sur cet écran comme explication

**Comment by arnaudlevy** [comment]
Dans la description, il faudra fournir des indicateurs pour guider une réponse saine

**Comment by Dannebicque** [comment]
> [1. Mettre en oeuvre sa/ses compétences](https://orebut.iut.fr/labset/criteres/evaluation/1)
> 
> s'affiche dans le show de la SAE en "Vise la compétence..."
> 
> Par ailleurs l'url crash

Pas compris ce que tu voulais dire

**Comment by Dannebicque** [comment]
> <img alt="image" width="1710" src="https://user-images.githubusercontent.com/2088968/216570322-cb90b51b-7e93-4f99-866f-d58426e1e2ce.png">
> 
> Ajouter aussi un champ de description du critère, que l'on ajouterait sur cet écran comme explication

J'ajoute.

**Comment by arnaudlevy** [comment]
Aujourd'hui le critère a un titre, "1. Mettre en oeuvre sa/ses compétences". Mais en fait il faudrait 2 champs, 1 pour la question ("1. Mettre en oeuvre sa/ses compétences") et un pour l'affichage ("Vise la compétence...")

<img width="791" alt="image" src="https://user-images.githubusercontent.com/2088968/216921649-9f07256b-8e60-4fe5-ba17-7c8f0cc21f0f.png">

**Comment by Dannebicque** [comment]
OK, ajouté les deux description et libellé pour la partie affichage. Mis à jour dans le show, et les formulaires
