### ISSUE TITLE
Tableau du référentiel

### ISSUE THREAD

**Issue by arnaudlevy** [Dannebicque/redigeTonBut#6]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/2088968/216571223-c3e3d539-3999-478e-9b57-e7e23d931c15.png">

- [ ] Le remonter dans la page (c'est important)
- [x] Mettre les composantes essentielles et pas les AC

**Comment by Dannebicque** [comment]
Remonter sur le show ?

**Comment by arnaudlevy** [comment]
si j'ai bien compris François, dans la page show, il est en bas, il faudrait qu'il soit plus haut parce que c'est là dessus que l'on travaille (peut-être juste sous l'évaluation ?)

**Comment by Dannebicque** [comment]
Fait
